sudo: required
dist: trusty
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
env:
  global:
install:
  # install latest Hibernate OGM snapshot
  - git clone https://github.com/hibernate/hibernate-ogm.git
  - cd hibernate-ogm
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N -q io.takari:maven:wrapper
  - ./mvnw -v
  - travis_wait ./mvnw install -B -q -s settings-example.xml -am -pl bom,core -DskipITs -DskipDistro -DskipDocs -DskipTests
  - cd ..
  - pwd
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  # first run to download all the Maven dependencies without logging
  - travis_wait ./mvnw install -B -q -s settings-example.xml -Ptest -DskipTests=true -Dmaven.javadoc.skip=true -DskipDistro=true 
  # we run checkstyle first to fail fast if there is a styling error
  - ./mvnw -s settings-example.xml -DskipDistro=true checkstyle:check
matrix:
  fast_finish: true
script:
  - ./mvnw -s settings-example.xml clean install
#  - ./mvnw -s settings-example.xml clean install -DskipTests && ./mvnw -s settings-example.xml clean install -pl modules,integrationtest
#  - ./mvnw -s settings-example.xml clean install -DskipTests && ./mvnw -s settings-example.xml clean install -pl documentation,distribution
after_script:
  - rm -rf $HOME/.m2/repository/org/hibernate/ogm/
